// tb_realdata.sv — replay REAL Qwen2 attention traces through the TIU.
//
// Reads rtl/tb/testvectors/tiu_trace.hex (generated by analysis/gen_tiu_testvectors.py
// from a Qwen2-0.5B forward pass) and drives the LOAD / ACC / EVICT op stream into the
// DUT, checking that every eviction victim matches the trace's expected slot (computed
// by the Python reference that mirrors the RTL argmin). This is the "does it evict the
// right heavy-hitters on real data" test, complementing the directed tb.
`timescale 1ns/1ps

module tb_realdata;
    localparam integer N_SLOTS      = 8;
    localparam integer SCORE_WIDTH  = 8;
    localparam integer WEIGHT_WIDTH = 8;
    localparam integer SLOT_WIDTH   = 3;

    reg clk = 0, rst_n = 0;
    reg acc_valid = 0; reg [SLOT_WIDTH-1:0] acc_slot = 0; reg [WEIGHT_WIDTH-1:0] acc_weight = 0;
    reg ld_valid = 0;  reg [SLOT_WIDTH-1:0] ld_slot = 0;
    reg evict_req = 0;
    reg [SCORE_WIDTH-1:0] tier_threshold = 0;
    wire [N_SLOTS-1:0] tier_keep;
    wire evict_valid; wire [SLOT_WIDTH-1:0] evict_slot; wire busy;

    token_importance_unit #(
        .N_SLOTS(N_SLOTS), .SCORE_WIDTH(SCORE_WIDTH), .WEIGHT_WIDTH(WEIGHT_WIDTH)
    ) dut (
        .clk(clk), .rst_n(rst_n),
        .acc_valid(acc_valid), .acc_slot(acc_slot), .acc_weight(acc_weight),
        .ld_valid(ld_valid), .ld_slot(ld_slot),
        .evict_req(evict_req), .evict_valid(evict_valid), .evict_slot(evict_slot),
        .tier_threshold(tier_threshold), .tier_keep(tier_keep),
        .busy(busy)
    );

    always #5 clk = ~clk;

    integer fd, r, code;
    integer op, slot, weight, exp;
    integer n_ops = 0, n_evict = 0, n_pass = 0;
    reg [1023:0] line;

    task drive_load(input [SLOT_WIDTH-1:0] s);
        begin @(negedge clk); ld_valid=1; ld_slot=s; @(posedge clk); #1 ld_valid=0; end
    endtask
    task drive_acc(input [SLOT_WIDTH-1:0] s, input [WEIGHT_WIDTH-1:0] w);
        begin @(negedge clk); acc_valid=1; acc_slot=s; acc_weight=w; @(posedge clk); #1 acc_valid=0; end
    endtask
    task drive_evict(input [SLOT_WIDTH-1:0] e);
        begin
            @(negedge clk); evict_req=1; @(posedge clk); #1 evict_req=0;
            wait (evict_valid == 1'b1); #1;
            n_evict = n_evict + 1;
            if (evict_slot === e[SLOT_WIDTH-1:0]) n_pass = n_pass + 1;
            else $display("  MISMATCH @op %0d: evict got %0d expected %0d", n_ops, evict_slot, e);
            @(posedge clk);
        end
    endtask

    initial begin
        rst_n = 0; @(posedge clk); @(posedge clk); rst_n = 1; @(posedge clk);

        fd = $fopen("tb/testvectors/tiu_trace.hex", "r");
        if (fd == 0) begin $display("ERROR: cannot open tiu_trace.hex"); $finish; end

        while (!$feof(fd)) begin
            code = $fgets(line, fd);
            // comment lines ("// ...") fail the %x parse -> r != 4 -> skipped
            r = $sscanf(line, "%x %x %x %x", op, slot, weight, exp);
            if (code != 0 && r == 4) begin
                n_ops = n_ops + 1;
                case (op)
                    0: drive_acc(slot[SLOT_WIDTH-1:0], weight[WEIGHT_WIDTH-1:0]);
                    1: drive_load(slot[SLOT_WIDTH-1:0]);
                    2: drive_evict(exp[SLOT_WIDTH-1:0]);
                endcase
            end
        end
        $fclose(fd);

        $display("");
        $display("Replay: %0d ops streamed, %0d evictions, %0d/%0d checks passed",
                 n_ops, n_evict, n_pass, n_evict);
        if (n_evict > 0 && n_pass == n_evict) $display("ALL TESTS PASSED");
        else $display("FAILED (%0d/%0d)", n_pass, n_evict);
        $finish;
    end
endmodule
